version: "3"
services:
  db:
    container_name: db
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=P@ssword
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
  api:
    container_name: api
    build:
      dockerfile: "./api/Dockerfile"
      context: ./
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: P@ssw0rd
      DB_NAME: to_do_app
    networks:
      - default
    ports:
      - "3001:3001"
  front:
    build:
      dockerfile: "./api/Dockerfile"
      context: ./
    networks:
      - default
    ports:
      - "3000:3000"
volumes:
  db:
